# Generated by Django 4.2.2 on 2023-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=15)),
            ],
        ),
    ]
